#!/bin/bash
# railway_services.sh — cria os 4 serviços Railway a partir do repositório
# Pré-requisito: railway login && railway link (projeto já criado)
# Uso: bash scripts/railway_services.sh

set -euo pipefail

echo "=== VIGÍA — Criando serviços Railway ==="
echo ""
echo "Este script documenta os comandos manuais necessários no painel Railway."
echo "Railway não suporta criação de múltiplos serviços via CLI em monorepo."
echo ""
echo "Execute estes passos no painel Railway (railway.app):"
echo ""
echo "1. Acesse seu projeto → New Service → GitHub Repo"
echo ""
echo "   ── backend ──────────────────────────────────────────────"
echo "   Name:             backend"
echo "   Root Directory:   vigia/backend"
echo "   Dockerfile:       Dockerfile"
echo "   Start Command:    /app/entrypoint.sh"
echo "   Health Check:     /api/ping"
echo ""
echo "   ── celery_worker ────────────────────────────────────────"
echo "   Name:             celery_worker"
echo "   Root Directory:   vigia/backend"
echo "   Dockerfile:       Dockerfile"
echo "   Start Command:    celery -A celery_app worker --loglevel=warning --concurrency=2 --max-tasks-per-child=100"
echo "   Health Check:     (none)"
echo ""
echo "   ── celery_beat ──────────────────────────────────────────"
echo "   Name:             celery_beat"
echo "   Root Directory:   vigia/backend"
echo "   Dockerfile:       Dockerfile"
echo "   Start Command:    celery -A celery_app beat --loglevel=warning --schedule /tmp/celerybeat-schedule"
echo "   Health Check:     (none)"
echo ""
echo "   ── frontend ─────────────────────────────────────────────"
echo "   Name:             frontend"
echo "   Root Directory:   vigia/frontend"
echo "   Dockerfile:       Dockerfile"
echo "   Start Command:    node server.js"
echo "   Health Check:     /"
echo "   Build Args:       NEXT_PUBLIC_API_URL=\${{backend.RAILWAY_PRIVATE_DOMAIN}}"
echo ""
echo "2. Adicione PostgreSQL e Redis via New Service → Database"
echo ""
echo "3. Configure as variáveis de ambiente em cada serviço:"
echo "   bash scripts/setup_railway.sh --service backend"
echo "   (repita para celery_worker e celery_beat com as mesmas vars)"
echo ""
echo "4. Deploy:"
echo "   railway up --service backend"
echo "   railway up --service celery_worker"
echo "   railway up --service celery_beat"
echo "   railway up --service frontend"
echo ""
echo "5. Validar:"
echo "   bash scripts/validate_deploy.sh https://api-url.railway.app https://frontend-url.railway.app"
