CULTURAS_SEED = [
    {
        "nome": "Soja",
        "nome_cientifico": "Glycine max",
        "categoria": "graos",
        "subcategoria": "oleaginosas",
        "ciclo_dias_min": 100,
        "ciclo_dias_max": 150,
        "ndvi_fases": {"plantio": 0.2, "vegetativo": 0.6, "florescimento": 0.75, "maturacao": 0.4},
        "temp_ideal_min": 20,
        "temp_ideal_max": 30,
        "chuva_ciclo_min_mm": 450,
        "chuva_ciclo_max_mm": 800,
        "pragas_principais": ["ferrugem_asiatica", "percevejo", "lagarta_helicoverpa"],
        "paises_producao": ["BRA", "ARG", "PRY", "BOL", "URU"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "sc60kg",
        "calendarios": [
            {"pais": "BRA", "estado": "MT", "regiao": "Mato Grosso", "meses_plantio": [10, 11], "meses_colheita": [2, 3], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "BRA", "estado": "PR", "regiao": "Paraná", "meses_plantio": [10, 11], "meses_colheita": [2, 3], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "ARG", "estado": None, "regiao": "Pampas", "meses_plantio": [11, 12], "meses_colheita": [3, 4], "sistema": "sequeiro", "fonte": "SIIA"},
        ],
    },
    {
        "nome": "Milho",
        "nome_cientifico": "Zea mays",
        "categoria": "graos",
        "subcategoria": "cereais",
        "ciclo_dias_min": 90,
        "ciclo_dias_max": 130,
        "ndvi_fases": {"plantio": 0.25, "vegetativo": 0.65, "pendoamento": 0.75, "maturacao": 0.35},
        "temp_ideal_min": 18,
        "temp_ideal_max": 32,
        "chuva_ciclo_min_mm": 350,
        "chuva_ciclo_max_mm": 700,
        "pragas_principais": ["lagarta_do_cartucho", "cigarrinha", "percevejo_barriga_verde"],
        "paises_producao": ["BRA", "ARG", "PRY", "BOL"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "sc60kg",
        "calendarios": [
            {"pais": "BRA", "estado": "MT", "regiao": "Mato Grosso", "meses_plantio": [1, 2], "meses_colheita": [6, 7], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "ARG", "estado": None, "regiao": "Córdoba", "meses_plantio": [10, 11], "meses_colheita": [3, 4], "sistema": "sequeiro", "fonte": "SIIA"},
        ],
    },
    {
        "nome": "Café Arábica",
        "nome_cientifico": "Coffea arabica",
        "categoria": "commodities",
        "subcategoria": "bebidas",
        "ciclo_dias_min": 210,
        "ciclo_dias_max": 240,
        "ndvi_fases": {"florescimento": 0.55, "chumbinho": 0.6, "granacao": 0.65, "maturacao": 0.55},
        "temp_ideal_min": 18,
        "temp_ideal_max": 23,
        "chuva_ciclo_min_mm": 1200,
        "chuva_ciclo_max_mm": 1800,
        "pragas_principais": ["broca_do_cafe", "ferrugem_cafe", "bicho_mineiro"],
        "paises_producao": ["BRA", "COL", "PER", "BOL"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "sc60kg",
        "calendarios": [
            {"pais": "BRA", "estado": "MG", "regiao": "Sul de Minas", "meses_plantio": [10, 11], "meses_colheita": [5, 6, 7, 8], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "COL", "estado": None, "regiao": "Eje Cafetero", "meses_plantio": [4, 5, 10], "meses_colheita": [9, 10, 11, 12], "sistema": "sequeiro", "fonte": "FNC"},
        ],
    },
    {
        "nome": "Cana-de-açúcar",
        "nome_cientifico": "Saccharum officinarum",
        "categoria": "commodities",
        "subcategoria": "energeticos",
        "ciclo_dias_min": 300,
        "ciclo_dias_max": 540,
        "ndvi_fases": {"brotacao": 0.3, "perfilhamento": 0.65, "grande_crescimento": 0.8, "maturacao": 0.6},
        "temp_ideal_min": 21,
        "temp_ideal_max": 35,
        "chuva_ciclo_min_mm": 1000,
        "chuva_ciclo_max_mm": 1500,
        "pragas_principais": ["broca_cana", "cigarrinha_da_raiz"],
        "paises_producao": ["BRA", "COL", "PER", "ARG"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "t",
        "calendarios": [
            {"pais": "BRA", "estado": "SP", "regiao": "Centro-Sul", "meses_plantio": [1, 2, 3], "meses_colheita": [4, 5, 6, 7, 8, 9, 10, 11], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Arroz",
        "nome_cientifico": "Oryza sativa",
        "categoria": "graos",
        "subcategoria": "cereais",
        "ciclo_dias_min": 105,
        "ciclo_dias_max": 150,
        "ndvi_fases": {"plantio": 0.3, "perfilhamento": 0.65, "paniculas": 0.7, "maturacao": 0.45},
        "temp_ideal_min": 22,
        "temp_ideal_max": 30,
        "chuva_ciclo_min_mm": 500,
        "chuva_ciclo_max_mm": 1200,
        "pragas_principais": ["brusone", "escaldadura", "percevejo_barriga_verde"],
        "paises_producao": ["BRA", "URU", "ARG", "PRY", "BOL", "PER"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "sc50kg",
        "calendarios": [
            {"pais": "BRA", "estado": "RS", "regiao": "Rio Grande do Sul", "meses_plantio": [10, 11], "meses_colheita": [2, 3], "sistema": "irrigado", "fonte": "CONAB"},
            {"pais": "URU", "estado": None, "regiao": "Uruguay", "meses_plantio": [11, 12], "meses_colheita": [3, 4], "sistema": "irrigado", "fonte": "OPYPA"},
        ],
    },
    {
        "nome": "Feijão",
        "nome_cientifico": "Phaseolus vulgaris",
        "categoria": "graos",
        "subcategoria": "leguminosas",
        "ciclo_dias_min": 65,
        "ciclo_dias_max": 100,
        "ndvi_fases": {"emergencia": 0.25, "vegetativo": 0.55, "florescimento": 0.65, "maturacao": 0.35},
        "temp_ideal_min": 18,
        "temp_ideal_max": 28,
        "chuva_ciclo_min_mm": 250,
        "chuva_ciclo_max_mm": 500,
        "pragas_principais": ["mosca_branca", "antracnose", "vaquinha"],
        "paises_producao": ["BRA", "ARG", "PRY", "BOL"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "sc60kg",
        "calendarios": [
            {"pais": "BRA", "estado": "PR", "regiao": "Paraná", "meses_plantio": [1, 2, 7, 8], "meses_colheita": [4, 5, 10, 11], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Trigo",
        "nome_cientifico": "Triticum aestivum",
        "categoria": "graos",
        "subcategoria": "cereais",
        "ciclo_dias_min": 100,
        "ciclo_dias_max": 130,
        "ndvi_fases": {"emergencia": 0.25, "afilhamento": 0.55, "espiamento": 0.65, "maturacao": 0.3},
        "temp_ideal_min": 12,
        "temp_ideal_max": 22,
        "chuva_ciclo_min_mm": 350,
        "chuva_ciclo_max_mm": 600,
        "pragas_principais": ["ferrugem_folha", "brusone", "giberela"],
        "paises_producao": ["BRA", "ARG", "URU"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "t",
        "calendarios": [
            {"pais": "BRA", "estado": "PR", "regiao": "Paraná", "meses_plantio": [5, 6, 7], "meses_colheita": [10, 11], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "ARG", "estado": None, "regiao": "Pampas", "meses_plantio": [5, 6, 7], "meses_colheita": [11, 12], "sistema": "sequeiro", "fonte": "SIIA"},
        ],
    },
    {
        "nome": "Tomate",
        "nome_cientifico": "Solanum lycopersicum",
        "categoria": "hortifruti",
        "subcategoria": "solanaceas",
        "ciclo_dias_min": 80,
        "ciclo_dias_max": 120,
        "ndvi_fases": {"muda": 0.3, "vegetativo": 0.6, "florescimento": 0.65, "frutificacao": 0.6},
        "temp_ideal_min": 18,
        "temp_ideal_max": 26,
        "chuva_ciclo_min_mm": 400,
        "chuva_ciclo_max_mm": 600,
        "pragas_principais": ["tuta_absoluta", "mosca_branca", "requeima"],
        "paises_producao": ["BRA", "ARG", "PER", "CHL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "cx",
        "calendarios": [
            {"pais": "BRA", "estado": "GO", "regiao": "Goiás", "meses_plantio": [4, 5, 7, 8], "meses_colheita": [7, 8, 10, 11], "sistema": "irrigado", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Alho",
        "nome_cientifico": "Allium sativum",
        "categoria": "hortifruti",
        "subcategoria": "alliaceas",
        "ciclo_dias_min": 120,
        "ciclo_dias_max": 180,
        "ndvi_fases": {"plantio": 0.2, "vegetativo": 0.5, "bulbificacao": 0.45},
        "temp_ideal_min": 10,
        "temp_ideal_max": 20,
        "chuva_ciclo_min_mm": 350,
        "chuva_ciclo_max_mm": 600,
        "pragas_principais": ["tripes", "ferrugem_alho"],
        "paises_producao": ["BRA", "ARG", "CHL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "caixa",
        "calendarios": [
            {"pais": "BRA", "estado": "MG", "regiao": "Curvelo", "meses_plantio": [3, 4, 5], "meses_colheita": [8, 9, 10], "sistema": "irrigado", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Cebola",
        "nome_cientifico": "Allium cepa",
        "categoria": "hortifruti",
        "subcategoria": "alliaceas",
        "ciclo_dias_min": 100,
        "ciclo_dias_max": 160,
        "ndvi_fases": {"muda": 0.25, "vegetativo": 0.55, "bulbificacao": 0.5},
        "temp_ideal_min": 13,
        "temp_ideal_max": 24,
        "chuva_ciclo_min_mm": 350,
        "chuva_ciclo_max_mm": 600,
        "pragas_principais": ["tripes", "alternaria"],
        "paises_producao": ["BRA", "ARG", "CHL", "PER"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "kg",
        "calendarios": [
            {"pais": "BRA", "estado": "SC", "regiao": "Alto Vale", "meses_plantio": [3, 4], "meses_colheita": [11, 12], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Batata",
        "nome_cientifico": "Solanum tuberosum",
        "categoria": "hortifruti",
        "subcategoria": "tuberosas",
        "ciclo_dias_min": 90,
        "ciclo_dias_max": 130,
        "ndvi_fases": {"emergencia": 0.3, "vegetativo": 0.65, "florescimento": 0.6, "maturacao": 0.4},
        "temp_ideal_min": 15,
        "temp_ideal_max": 22,
        "chuva_ciclo_min_mm": 400,
        "chuva_ciclo_max_mm": 700,
        "pragas_principais": ["requeima", "pulgao_batata", "vira_cabeca"],
        "paises_producao": ["BRA", "ARG", "PER", "BOL", "CHL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "sc50kg",
        "calendarios": [
            {"pais": "BRA", "estado": "MG", "regiao": "Sul de Minas", "meses_plantio": [1, 2, 7, 8], "meses_colheita": [4, 5, 11, 12], "sistema": "irrigado", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Mandioca",
        "nome_cientifico": "Manihot esculenta",
        "categoria": "hortifruti",
        "subcategoria": "tuberosas",
        "ciclo_dias_min": 180,
        "ciclo_dias_max": 360,
        "ndvi_fases": {"brotacao": 0.3, "vegetativo": 0.65, "maturacao": 0.5},
        "temp_ideal_min": 20,
        "temp_ideal_max": 35,
        "chuva_ciclo_min_mm": 600,
        "chuva_ciclo_max_mm": 1500,
        "pragas_principais": ["mosca_branca", "acaro_verde", "bacteriose"],
        "paises_producao": ["BRA", "COL", "PER", "PRY", "BOL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "t",
        "calendarios": [
            {"pais": "BRA", "estado": "BA", "regiao": "Semiárido", "meses_plantio": [11, 12], "meses_colheita": [9, 10, 11], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Açaí",
        "nome_cientifico": "Euterpe oleracea",
        "categoria": "frutas",
        "subcategoria": "palmeiras",
        "ciclo_dias_min": 1095,
        "ciclo_dias_max": 1460,
        "ndvi_fases": {"muda": 0.4, "producao": 0.7},
        "temp_ideal_min": 24,
        "temp_ideal_max": 30,
        "chuva_ciclo_min_mm": 1800,
        "chuva_ciclo_max_mm": 3000,
        "pragas_principais": ["anel_vermelho", "podridao_da_base"],
        "paises_producao": ["BRA", "PER", "BOL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "litro",
        "calendarios": [
            {"pais": "BRA", "estado": "PA", "regiao": "Baixo Amazonas", "meses_plantio": [3, 4], "meses_colheita": [7, 8, 9, 10, 11, 12], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Banana",
        "nome_cientifico": "Musa spp.",
        "categoria": "frutas",
        "subcategoria": "musaceas",
        "ciclo_dias_min": 270,
        "ciclo_dias_max": 360,
        "ndvi_fases": {"muda": 0.5, "vegetativo": 0.75, "embandeiramento": 0.7, "maturacao": 0.6},
        "temp_ideal_min": 18,
        "temp_ideal_max": 35,
        "chuva_ciclo_min_mm": 1000,
        "chuva_ciclo_max_mm": 2000,
        "pragas_principais": ["mal_panama", "sigatoka_negra", "moko"],
        "paises_producao": ["BRA", "COL", "ECU", "PER", "BOL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "kg",
        "calendarios": [
            {"pais": "BRA", "estado": "SP", "regiao": "Vale do Ribeira", "meses_plantio": [8, 9, 10], "meses_colheita": [1, 2, 3, 4, 5, 6], "sistema": "irrigado", "fonte": "CONAB"},
            {"pais": "COL", "estado": None, "regiao": "Urabá", "meses_plantio": [1, 2, 3], "meses_colheita": [10, 11, 12], "sistema": "irrigado", "fonte": "Asohofrucol"},
        ],
    },
    {
        "nome": "Abacate",
        "nome_cientifico": "Persea americana",
        "categoria": "frutas",
        "subcategoria": "lauraceas",
        "ciclo_dias_min": 365,
        "ciclo_dias_max": 547,
        "ndvi_fases": {"vegetativo": 0.65, "florescimento": 0.6, "frutificacao": 0.68},
        "temp_ideal_min": 18,
        "temp_ideal_max": 26,
        "chuva_ciclo_min_mm": 800,
        "chuva_ciclo_max_mm": 1600,
        "pragas_principais": ["phytophthora", "tripes_da_flor", "colletotrichum"],
        "paises_producao": ["BRA", "CHL", "PER", "COL", "MEX"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "cx",
        "calendarios": [
            {"pais": "BRA", "estado": "SP", "regiao": "São Paulo", "meses_plantio": [10, 11], "meses_colheita": [6, 7, 8, 9], "sistema": "irrigado", "fonte": "CONAB"},
            {"pais": "CHL", "estado": None, "regiao": "Valparaíso", "meses_plantio": [9, 10], "meses_colheita": [10, 11, 12, 1], "sistema": "irrigado", "fonte": "ODEPA"},
        ],
    },
    {
        "nome": "Manga",
        "nome_cientifico": "Mangifera indica",
        "categoria": "frutas",
        "subcategoria": "anacardiaceae",
        "ciclo_dias_min": 90,
        "ciclo_dias_max": 150,
        "ndvi_fases": {"florescimento": 0.6, "chumbinho": 0.65, "maturacao": 0.6},
        "temp_ideal_min": 24,
        "temp_ideal_max": 35,
        "chuva_ciclo_min_mm": 500,
        "chuva_ciclo_max_mm": 1200,
        "pragas_principais": ["antracnose", "mosca_das_frutas", "oidiose"],
        "paises_producao": ["BRA", "PER", "ECU", "COL"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "cx",
        "calendarios": [
            {"pais": "BRA", "estado": "BA", "regiao": "Vale do São Francisco", "meses_plantio": [6, 7], "meses_colheita": [11, 12, 1], "sistema": "irrigado", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Quinoa",
        "nome_cientifico": "Chenopodium quinoa",
        "categoria": "graos",
        "subcategoria": "andinas",
        "ciclo_dias_min": 90,
        "ciclo_dias_max": 220,
        "ndvi_fases": {"emergencia": 0.3, "vegetativo": 0.55, "paniculamento": 0.6, "maturacao": 0.35},
        "temp_ideal_min": 5,
        "temp_ideal_max": 20,
        "chuva_ciclo_min_mm": 200,
        "chuva_ciclo_max_mm": 700,
        "pragas_principais": ["mildio", "afideos"],
        "paises_producao": ["BOL", "PER", "ECU", "COL", "CHL", "ARG"],
        "preco_referencia_fonte": "FAO",
        "unidade": "kg",
        "calendarios": [
            {"pais": "BOL", "estado": None, "regiao": "Altiplano", "meses_plantio": [8, 9, 10], "meses_colheita": [3, 4, 5], "sistema": "sequeiro", "altitude_min_m": 3500, "altitude_max_m": 4200, "fonte": "INIAF"},
            {"pais": "PER", "estado": None, "regiao": "Puno", "meses_plantio": [9, 10], "meses_colheita": [4, 5], "sistema": "sequeiro", "altitude_min_m": 3800, "altitude_max_m": 4500, "fonte": "MINAGRI"},
        ],
    },
    {
        "nome": "Algodão",
        "nome_cientifico": "Gossypium hirsutum",
        "categoria": "commodities",
        "subcategoria": "fibras",
        "ciclo_dias_min": 150,
        "ciclo_dias_max": 210,
        "ndvi_fases": {"emergencia": 0.25, "vegetativo": 0.6, "florescimento": 0.65, "maturacao": 0.35},
        "temp_ideal_min": 22,
        "temp_ideal_max": 35,
        "chuva_ciclo_min_mm": 500,
        "chuva_ciclo_max_mm": 800,
        "pragas_principais": ["bicudo_algodao", "mosca_branca", "curuquere"],
        "paises_producao": ["BRA", "ARG", "PRY"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "@15kg",
        "calendarios": [
            {"pais": "BRA", "estado": "MT", "regiao": "Mato Grosso", "meses_plantio": [12, 1, 2], "meses_colheita": [6, 7, 8], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Laranja",
        "nome_cientifico": "Citrus sinensis",
        "categoria": "frutas",
        "subcategoria": "citrus",
        "ciclo_dias_min": 180,
        "ciclo_dias_max": 270,
        "ndvi_fases": {"florescimento": 0.6, "chumbinho": 0.65, "maturacao": 0.6},
        "temp_ideal_min": 15,
        "temp_ideal_max": 30,
        "chuva_ciclo_min_mm": 1000,
        "chuva_ciclo_max_mm": 1500,
        "pragas_principais": ["greening_hlb", "ácaro_da_falsa_ferrugem", "mosca_das_frutas"],
        "paises_producao": ["BRA", "ARG", "URU", "PER"],
        "preco_referencia_fonte": "CEPEA",
        "unidade": "cx",
        "calendarios": [
            {"pais": "BRA", "estado": "SP", "regiao": "Cinturão Citrícola", "meses_plantio": [6, 7], "meses_colheita": [6, 7, 8, 9, 10, 11, 12], "sistema": "sequeiro", "fonte": "CONAB"},
        ],
    },
    {
        "nome": "Uva",
        "nome_cientifico": "Vitis vinifera",
        "categoria": "frutas",
        "subcategoria": "vitaceas",
        "ciclo_dias_min": 150,
        "ciclo_dias_max": 210,
        "ndvi_fases": {"brotacao": 0.35, "florescimento": 0.6, "frutificacao": 0.7, "maturacao": 0.55},
        "temp_ideal_min": 15,
        "temp_ideal_max": 28,
        "chuva_ciclo_min_mm": 400,
        "chuva_ciclo_max_mm": 700,
        "pragas_principais": ["mildio", "oidiose", "botrytis"],
        "paises_producao": ["BRA", "ARG", "CHL", "URU", "PER"],
        "preco_referencia_fonte": "CEASA",
        "unidade": "kg",
        "calendarios": [
            {"pais": "BRA", "estado": "RS", "regiao": "Serra Gaúcha", "meses_plantio": [8, 9], "meses_colheita": [1, 2, 3], "sistema": "sequeiro", "fonte": "CONAB"},
            {"pais": "ARG", "estado": None, "regiao": "Mendoza", "meses_plantio": [9, 10], "meses_colheita": [2, 3, 4], "sistema": "irrigado", "fonte": "INV"},
            {"pais": "CHL", "estado": None, "regiao": "Valle Central", "meses_plantio": [9, 10], "meses_colheita": [1, 2, 3], "sistema": "irrigado", "fonte": "ODEPA"},
        ],
    },
]
