FATORES_DEMANDA = [
    {
        "nome": "Apostas online (Bets)",
        "tipo": "reducao_orcamento",
        "impacto_direcao": "reducao",
        "impacto_pct": 13,
        "culturas_afetadas": ["hortifruti_geral", "carne", "frutas_premium"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["C", "D", "E"],
        "fonte_dado": "Kantar Q2/2025 — 13% do orçamento A&B redirecionado para bets",
        "url_fonte": "https://www.kantar.com/brazil/inspiration/consumo/2025",
        "confianca_pct": 85,
        "ativo": True,
    },
    {
        "nome": "GLP-1 (Ozempic, Mounjaro, Wegovy)",
        "tipo": "reducao_apetite",
        "impacto_direcao": "reducao",
        "impacto_pct": 12,
        "culturas_afetadas": ["cana_acucar", "cacau", "batata", "mandioca"],
        "paises_afetados": ["BRA", "ARG", "CHL"],
        "classes_renda_afetadas": ["A", "B"],
        "fonte_dado": "IQVIA — vendas GLP-1 cresceram +600% BR 2018→2024. Quebra patente 2026.",
        "url_fonte": "https://www.iqvia.com/latam",
        "confianca_pct": 90,
        "ativo": True,
    },
    {
        "nome": "Copa do Mundo 2026",
        "tipo": "sazonalidade",
        "impacto_direcao": "aumento",
        "impacto_pct": 25,
        "culturas_afetadas": ["milho_verde", "amendoim", "pipoca"],
        "paises_afetados": ["BRA", "ARG", "URU", "COL"],
        "classes_renda_afetadas": ["A", "B", "C", "D"],
        "fonte_dado": "NielsenIQ 2026 — snacks +25% durante jogos, refeição formal -25%",
        "confianca_pct": 80,
        "ativo": True,
    },
    {
        "nome": "El Niño formação 2026",
        "tipo": "climatico",
        "impacto_direcao": "reducao",
        "impacto_pct": 15,
        "culturas_afetadas": ["soja", "milho", "trigo"],
        "paises_afetados": ["BRA", "ARG", "PRY"],
        "classes_renda_afetadas": ["A", "B", "C", "D", "E"],
        "fonte_dado": "NOAA CPC — 61% prob El Niño ago-out 2026, 90%+ nov-jan 2027",
        "url_fonte": "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/lanina/enso_evolution-status-fcsts-web.pdf",
        "confianca_pct": 61,
        "ativo": True,
    },
    {
        "nome": "Festas Juninas",
        "tipo": "sazonalidade",
        "impacto_direcao": "aumento",
        "impacto_pct": 35,
        "culturas_afetadas": ["milho_verde", "abobora", "amendoim", "batata_doce"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["A", "B", "C", "D"],
        "fonte_dado": "Sazonalidade histórica CEASA — junho-julho",
        "confianca_pct": 95,
        "ativo": True,
    },
    {
        "nome": "Carnaval",
        "tipo": "sazonalidade",
        "impacto_direcao": "reducao",
        "impacto_pct": 40,
        "culturas_afetadas": ["hortifruti_fresco"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["A", "B", "C", "D"],
        "fonte_dado": "Consumo doméstico de hortifruti cai ~40% — pessoa come fora",
        "confianca_pct": 90,
        "ativo": True,
    },
    {
        "nome": "Inflação alimentos 2025",
        "tipo": "cambial",
        "impacto_direcao": "reducao",
        "impacto_pct": 8,
        "culturas_afetadas": ["cafe", "pimentao", "cacau"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["C", "D", "E"],
        "fonte_dado": "IBGE — café +41,84%, pimentão +29,93%, chocolate +27,84%",
        "url_fonte": "https://www.ibge.gov.br/explica/inflacao.php",
        "confianca_pct": 99,
        "ativo": True,
    },
    {
        "nome": "Geração Z — refeições menos estruturadas",
        "tipo": "geracional",
        "impacto_direcao": "reducao",
        "impacto_pct": 15,
        "culturas_afetadas": ["hortalicas_cozimento_longo"],
        "paises_afetados": ["BRA", "ARG", "CHL", "COL"],
        "classes_renda_afetadas": ["A", "B", "C"],
        "fonte_dado": "NielsenIQ 2026 — refeições formais -15% vs 2019, preparo -6%",
        "confianca_pct": 75,
        "ativo": True,
    },
    {
        "nome": "Tendência saúde e orgânicos",
        "tipo": "sazonalidade",
        "impacto_direcao": "aumento",
        "impacto_pct": 20,
        "culturas_afetadas": ["acai", "mirtilo", "quinoa", "abacate", "brocolis", "couve"],
        "paises_afetados": ["BRA", "CHL", "PER"],
        "classes_renda_afetadas": ["A", "B"],
        "fonte_dado": "Mercado orgânicos R$ 6,5 bi 2021 — crescimento 20%/ano",
        "confianca_pct": 85,
        "ativo": True,
    },
    {
        "nome": "Câmbio USD/BRL",
        "tipo": "cambial",
        "impacto_direcao": "aumento",
        "impacto_pct": 10,
        "culturas_afetadas": ["alho_importado_china", "trigo_importado"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["A", "B", "C", "D", "E"],
        "fonte_dado": "Banco Central do Brasil — USD/BRL 5,172 (jun/2026)",
        "url_fonte": "https://api.bcb.gov.br/dados/serie/bcdata.sgs.10813/dados",
        "confianca_pct": 99,
        "ativo": True,
    },
    {
        "nome": "Baixo desemprego 2026",
        "tipo": "sazonalidade",
        "impacto_direcao": "aumento",
        "impacto_pct": 8,
        "culturas_afetadas": ["proteinas", "hortifruti_premium"],
        "paises_afetados": ["BRA"],
        "classes_renda_afetadas": ["C", "D"],
        "fonte_dado": "PNAD Jun/2026 — desemprego 5,2% — mínimo histórico",
        "url_fonte": "https://www.ibge.gov.br/explica/desemprego.php",
        "confianca_pct": 99,
        "ativo": True,
    },
    {
        "nome": "Epidemias e alertas ANVISA",
        "tipo": "epidemia",
        "impacto_direcao": "reducao",
        "impacto_pct": 100,
        "culturas_afetadas": [],
        "paises_afetados": ["BRA", "ARG", "CHL", "COL", "PER"],
        "classes_renda_afetadas": ["A", "B", "C", "D", "E"],
        "fonte_dado": "Monitoramento contínuo ANVISA + Ministério Saúde",
        "url_fonte": "https://www.gov.br/anvisa/pt-br",
        "confianca_pct": 95,
        "ativo": True,
    },
]
